module(Exray.Core.Random.Loader)
interface([NIF, CNode])
callback(:load)
callback(:upgrade)
state_type("State")

spec(set_random_seed(seed :: unsigned) :: :ok)
spec(get_random_value(min :: int, max :: int) :: random_value :: int)
spec(load_random_sequence(count :: unsigned, min :: int, max :: int) :: random_sequence :: [int])
spec(unload_random_sequence(sequence :: [int]) :: :ok)
